spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: userdb
      auto-index-creation: true

server:
  port: 8000
  servlet:
    context-path: /

logging:
  level:
    com.example: DEBUG
    org.springframework.data.mongodb: INFO
