spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: userdb
      auto-index-creation: true

server:
  port: 8000
  servlet:
    context-path: /

logging:
  level:
    com.example: DEBUG
    org.springframework.data.mongodb: INFO

# МОНИТОРИНГ
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info
      base-path: /actuator
    enabled-by-default: true
  endpoint:
    health:
      show-details: always
      show-components: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
    web:
      server:
        request:
          autotime:
            enabled: true
  server:
    port: 8001  # Дополнительный порт для actuator