apiVersion: v1
kind: ConfigMap
metadata:
  name: user-app-config
  labels:
    app: user-app
data:
  application.yml: |
    server:
      port: 8000
      servlet:
        context-path: /
    
    spring:
      data:
        mongodb:
          auto-index-creation: true
    
    logging:
      level:
        com.example: INFO
        org.springframework.data.mongodb.core: DEBUG