apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  labels:
    app: user-app
type: Opaque
data:
  uri: bW9uZ29kYjovL2FwcC11c2VyOmFwcDEyM0BteS1tb25nb2RiOjI3MDE3L3VzZXJkYg==  # mongodb://app-user:app123@my-mongodb:27017/userdb
  username: YXBwLXVzZXI=  # app-user
  password: YXBwMTIz      # app123